substitutions:
  name: m5stack-atom-echo-your-id
  friendly_name: Atom Echo Your Name
  media_player_service: notify.any_media_player_service
  key: your_key

packages:
  m5stack.atom-echo-voice-assistant-no-speaker:
    url: https://github.com/TheDeadEndLink/M5-Atom-Echo-Voice-Assistant-No-Speaker-Output
    ref: main
    file: m5stack-atom-echo-no-speaker.yaml
    refresh: 1s
